<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Primitives" Version="10.0.7" />
    <PackageVersion Include="Polyfill" Version="10.4.0" />
    <PackageVersion Include="TUnit" Version="1.65.63" />
  </ItemGroup>
</Project>
